services:
  - type: web
    name: jobwise-server
    env: node
    buildCommand: cd jobwise-server && npm install
    startCommand: cd jobwise-server && npm run dev
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://kumarvishvajeetsingh:Vishu8969@cluster0.ajsta.mongodb.net/jobwise?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: your-super-secret-jwt-key-change-in-production
      - key: JWT_EXPIRE
        value: 7d
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: development
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USER
        value: your-email@gmail.com
      - key: EMAIL_PASS
        value: your-app-password
      - key: CLIENT_URL
        value: https://jobwise-client.onrender.com

  - type: web
    name: jobwise-client
    env: static
    buildCommand: cd jobwise-client && npm install && npm run build
    staticPublishPath: jobwise-client/dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://jobwise-server.onrender.com/api
